In [1]:
import numpy as np

In [3]:
mylist = [1,2,3]
np.array(mylist)

array([1, 2, 3])

In [4]:
myarr = np.array(mylist)

In [5]:
myarr

array([1, 2, 3])

In [6]:
mylist1=[[1,2],[3,4],[5,6]]

In [7]:
myarr1 = np.array(mylist1)

In [8]:
myarr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
type(myarr)

numpy.ndarray

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [18]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [21]:
np.eye(1)

array([[1.]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.21947875, 0.3578518 , 0.21215088, 0.73753652, 0.6098426 ])

In [24]:
np.random.rand(1) # rand gives distribution of number between 0 to 1 but nit give 0

array([0.85928374])

In [27]:
np.random.rand(2,3)

array([[0.43004061, 0.57008599, 0.1326227 ],
       [0.77044651, 0.60457923, 0.50909324]])

In [28]:
np.random.randn(5) # randn is normal distribution and gives any number such that mena =0 and sigma =1

array([-0.59770817, -1.88123595,  1.45821228,  0.11757004, -0.96719424])

In [29]:
np.random.randn(5,2)

array([[-0.56715361,  0.78647212],
       [-0.81018986, -0.72388828],
       [ 0.35035189,  0.43160497],
       [-0.263951  ,  0.24999188],
       [-0.61233951, -0.13771201]])

In [30]:
np.random.randn(1)

array([0.00669444])

In [31]:
np.random.randint(0,100)

2

In [32]:
np.random.randint(0,100,5)

array([ 7, 51,  7, 95, 28])

In [33]:
np.random.randint(0,100,(4,5))

array([[37, 21, 39, 24,  3],
       [43, 18, 37,  2, 97],
       [50, 17, 23, 16, 12],
       [79, 26, 45, 52,  9]])

In [40]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [38]:
np.random.randint(4)

3

In [44]:
arr = np.arange(0,25)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [49]:
myarr = np.arange(0,1000,10)

In [50]:
myarr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510,
       520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640,
       650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770,
       780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900,
       910, 920, 930, 940, 950, 960, 970, 980, 990])

In [52]:
randarr =np.random.randint(0,100,(4,5))

In [53]:
randarr

array([[57, 21, 88, 48, 90],
       [58, 41, 91, 59, 79],
       [14, 61, 61, 46, 61],
       [50, 54, 63,  2, 50]])

In [54]:
randarr.max()

91

In [55]:
randarr.min()

2

In [56]:
randarr.argmax()

7

In [58]:
randarr.argmin()

18

In [60]:
randarr.dtype

dtype('int32')

In [67]:
arr1 = np.random.randint(0,10,6)

In [68]:
arr1

array([1, 9, 8, 9, 4, 1])

In [69]:
arr1.shape

(6,)

In [70]:
arr1.reshape(2,3)

array([[1, 9, 8],
       [9, 4, 1]])

In [71]:
arr1.shape

(6,)

In [72]:
arr1 = arr1.reshape(2,3)

In [73]:
arr1.shape

(2, 3)

In [74]:
arr1.reshape(6,1)

array([[1],
       [9],
       [8],
       [9],
       [4],
       [1]])

In [75]:
arr1.reshape(1,6)

array([[1, 9, 8, 9, 4, 1]])

In [2]:
import numpy as np
myarray = np.linspace(0,101,10)
myarray

array([  0.        ,  11.22222222,  22.44444444,  33.66666667,
        44.88888889,  56.11111111,  67.33333333,  78.55555556,
        89.77777778, 101.        ])

In [3]:
arr1 = np.arange(0,10)

In [4]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr1[2:6]

array([2, 3, 4, 5])

In [13]:
arr1[ : ]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr1[2]=[11,12,13]

ValueError: setting an array element with a sequence.

In [18]:
arr_2d = np.array([[4,5,6],[7,8,9],[10,11,12]])

In [19]:
arr_2d

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
arr_2d.shape

(3, 3)

In [23]:
arr_2d[0]

array([4, 5, 6])

In [24]:
arr_2d[0,2]

6

In [25]:
arr_2d[0][2]

6

In [26]:
arr_2d[0:2]

array([[4, 5, 6],
       [7, 8, 9]])

In [27]:
arr_2d[:2,1:]

array([[5, 6],
       [8, 9]])

In [28]:
## must read notes ed broadcasting and slicing

In [29]:
arr2 = np.arange(0,11,3)

In [30]:
arr2

array([0, 3, 6, 9])

In [31]:
arr2>4

array([False, False,  True,  True])

In [33]:
arr_bool = arr2>4

In [34]:
arr_bool

array([False, False,  True,  True])

In [35]:
arr2[arr_bool]

array([6, 9])

In [36]:
arr2[arr2>4]

array([6, 9])

In [37]:
arr2.shape

(4,)

In [51]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
a= dice_rolls[dice_rolls >2].shape


In [52]:
a

(19,)

In [53]:
a[0]

19

In [54]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
total_rolls_over_two=dice_rolls[dice_rolls >2].shape[0]

In [55]:
total_rolls_over_two

19